# Generated by Django 5.0 on 2023-12-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_imgurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
