# Generated by Django 5.0 on 2023-12-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_contact_user_confirmpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmpassword',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(),
        ),
    ]
